DATA: 
  TRAIN_DIR: 'datasets/my_train_data'
  TRAIN_ANNOTATION: 'datasets/annotations/train_annotation.json'
  VALIDATION_DIR: 'datasets/my_val_data'
  VALIDATION_ANNOTATION: 'datasets/annotations/val_annotation.json'

  MEAN_PIXEL: [123.7, 116.8, 103.9]
  MAX_GT_INSTANCES: 3
  NUM_CLASSES: 3  # number of classes + 1 (background)
  IMAGE_SIZE: 640
  IMAGE_CHANNELS: 3 # 3 for RGB, 1 for BW

MODEL:
  BACKBONE: 'ResNet101V2'  # 'ResNet50V2', 'ResNet101V2', 'ResNet152V2', 'ResNet50', 'ResNet101', 'ResNet152'
  FPN: 
    PYRAMID_SIZE: 256
    STRIDES: [8, 16, 32, 64, 128]
  # ROI_RESOLUTION must be divisible by ATTENTION_SIZE
  ROI_RESOLUTION: 56
  ATTENTION_SIZE: 14

TRAIN:
  METRICS: ['semantic', 'classification', 'centerness', 'location', 'blender']
  START_EPOCH: 0
  TRAINING: 1
  EPOCHS: 5
  BATCH_SIZE: 2
  OPTIMIZER:
    LEARNING_RATE: 0.01
    CLIP_VALUE: 0.5
  SEM_LOSS_WEIGHT: 1
