DATA:
  TRAIN_DIR: 'datasets/my_train_data'
  TRAIN_ANNOTATION: 'datasets/annotations/train_annotation.json'
  VALIDATION_DIR: 'datasets/my_val_data'
  VALIDATION_ANNOTATION: 'datasets/annotations/val_annotation.json'

  MEAN_PIXEL: [123.7, 116.8, 103.9]
  MAX_GT_INSTANCES: 3
  NUM_CLASSES: 3  # number of classes + 1 (background)
  IMAGE_SIZE: 640
  IMAGE_CHANNELS: 3 # 3 for RGB, 1 for BW

MODEL:
  TRAIN_BN: True
  USE_RPN_ROIS: True
  BACKBONE: 'ResNet101V2'  # 'ResNet50V2', 'ResNet101V2', 'ResNet152V2', 'ResNet50', 'ResNet101', 'ResNet152'
  BACKBONE_STRIDES: [4, 8, 16, 32, 64]
  USE_MINI_MASK: True
  MINI_MASK_SHAPE: [56, 56]
  MASK_POOL_SIZE: 14
  MASK_SHAPE: [28, 28]
  POOL_SIZE: 7

  PYRAMID_SIZE: 256
  STRIDES: [8, 16, 32, 64, 128]
  FPN_CLASSIF_FC_LAYERS_SIZE: 1024
  PRE_NMS_LIMIT: 6000
  ROI_POSITIVE_RATIO: 0.33
  TRAIN_ROIS_PER_IMAGE: 200
  RPN_BBOX_STD_DEV: [0.1, 0.1, 0.2, 0.2]
  BBOX_STD_DEV: [0.1, 0.1, 0.2, 0.2]
  RPN_ANCHOR_STRIDE: 1
  RPN_ANCHOR_RATIOS: [0.5, 1, 2]
  TOP_DOWN_PYRAMID_SIZE: 256
  RPN_ANCHOR_SCALES: [32, 64, 128, 256, 512]
  RPN_NMS_THRESHOLD: 0.7
  POST_NMS_ROIS_TRAINING: 2000
  POST_NMS_ROIS_INFERENCE: 1000


TRAIN:
  METRICS: ['semantic', 'classification', 'centerness', 'location', 'blender']
  START_EPOCH: 0
  TRAINING: 1
  EPOCHS: 5
  BATCH_SIZE: 2
  IMAGES_PER_GPU: 2
  OPTIMIZER:
    LEARNING_RATE: 0.01
    CLIP_VALUE: 0.5
  SEM_LOSS_WEIGHT: 1
